### ISSUE TITLE
What happens if you include the group address in a mentioned people only post

### ISSUE THREAD

**Issue by placoderm** [immers-space/guppe#66]
Sorry, didn't know where else to ask this.

I was going to give someone the group address in a DM, but then I wondered if the DM would then go out to the group.

Thanks for this app, by the way.

**Comment by BeeFox-sys** [comment]
hm yes probably, privacy settings in activity pub are trust, not strict. this means if they are not checked before sending, then it might get boosted to the entire group, however at the same time some instances might still respect the privacy over the boost, in any case, safer to break up a group adress

**Comment by wmurphyrd** [comment]
That's right - mentioning a group in a DM won't expose the contents of the DM to the group. 

Guppe never transmits the contents of your messages to anyone. It only sends along the message's unique identifier, so that other group members who already have permission to see that post will see it in the group. Within the confines of Mastodon's specific take on permissions, that means that only Public and Unlisted posts can appear in groups

**Comment by placoderm** [comment]
> That's right - mentioning a group in a DM won't expose the contents of the DM to the group.

Thanks! Maybe you could include that on the website.

Great service, thanks!
